[package]
name = "bench_utils"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Simple utilities to measure latency and synthesise functions with predictable latency."
repository = "https://github.com/pvillela/rust-bench-utils/tree/main"
documentation = "https://docs.rs/bench_utils/latest/bench_utils/"
readme = "README.md"
keywords = [
    "latency",
    "measurement",
    "performance",
    "benchmarking",
    "calibration",
]
categories = ["development-tools::profiling"]
exclude = ["CHANGELOG.md", "*.sh", ".gitignore", "examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basic_stats = { path = "../basic-stats", default-features = false, optional = true }
hdrhistogram = "7.5"
sha2 = { version = "0.10.9", optional = true }

[dev-dependencies]
statrs = "0.18"

[features]

# Public
default = ["_bench_one", "__core"] # should always be enabled for public use
busy_work = ["dep:sha2"]

# Shared with friends
_bench_diff = ["__core"] # for use by `bench_diff` crate

# Helper
__null = ["dep:basic_stats"]
__core = ["_friends_only", "basic_stats/normal", "basic_stats/aok"]

# Internal
_bench_one = []                         # not used by `bench_diff` create
_friends_only = []                      # only for self and `bench_diff` crate
_dev_utils = ["basic_stats/_dev_utils"]

[package.metadata.docs.rs]
features = ["busy_work"]

[[bench]]
name = "validate_bench_one"
harness = false
