[package]
name = "bench_utils"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Simple utilities to measure latency and synthesise functions with predictable latency."
repository = "https://github.com/pvillela/rust-bench-utils/tree/main"
documentation = "https://docs.rs/bench_utils/latest/bench_utils/"
readme = "README.md"
keywords = [
    "latency",
    "measurement",
    "performance",
    "benchmarking",
    "calibration",
]
categories = ["development-tools::profiling"]
exclude = ["CHANGELOG.md", "*.sh", ".gitignore", "examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basic_stats = { version = "1.0.0", default-features = false, features = [
    "normal",
    "aok",
] }
hdrhistogram = "7.5"
sha2 = { version = "0.10.9", optional = true }


[features]
default = [
    "_bench_one",
    "_friends_only",
] # should always be enabled for public use
busy_work = ["dep:sha2"]
_bench_diff = ["_friends_only"] # for use by `bench_diff` crate
_bench_one = [] # not used by `bench_diff` create
_friends_only = [] # only for self and `bench_diff` crate
_friends_only_test = [] # for tests, only for self and `bench_diff` crate

[package.metadata.docs.rs]
features = ["busy_work"]
