[package]
name = "bench_utils"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Simple utilities to measure latency and synthesise functions with predictable latency."
repository = "https://github.com/pvillela/rust-bench-utils/tree/main"
documentation = "https://docs.rs/bench_utils/latest/bench_utils/"
readme = "README.md"
keywords = [
    "latency",
    "measurement",
    "performance",
    "benchmarking",
    "calibration",
]
categories = ["development-tools::profiling"]
exclude = ["CHANGELOG.md", "*.sh", ".gitignore", "examples", "bin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basic_stats = { path = "../basic-stats", default-features = false, optional = true }
criterion = { version = "0.7.0", optional = true }
hdrhistogram = "7.5"
regex = { version = "1.11.1", optional = true }
sha2 = { version = "0.10.9", optional = true }

[dev-dependencies]
statrs = "0.18"

[features]

# Public
default = ["_bench_run", "__core"] # should always be enabled for public use
busy_work = ["dep:sha2"]
criterion = ["dep:criterion"]

# Shared with friends
_bench_diff = ["__core"] # for use by `bench_diff` crate

# Helper
__null = ["dep:basic_stats"]
__core = ["basic_stats/normal", "basic_stats/aok"]

# Internal
_bench_run = [] # not used by `bench_diff` crate default
_dev_utils = [
    "basic_stats/_dev_utils",
    "dep:regex",
] # enables approx_eq traits and macros, regex

[package.metadata.docs.rs]
features = ["busy_work"]

[[bench]]
name = "criterion_comp"
harness = false

[[bench]]
name = "criterion_plain"
harness = false

[[bench]]
name = "validate_bench_run"
harness = false
