use crate::{FpSeconds, latency, latency_n};

/// An iterator that yields latencies from interleaved individual executions or bulk executions of `K` closures.
///
/// For each invocation of `next()`, the iterator yields an array of size `K` with latencies associated with
/// invocations of each of the `K` closures. The method [`batch`](Self::batch) returns an option which indicates
/// whether batching is being used. If `batch()` returns `Some(n)` then each value yielded by `next()` should
/// be the average of latencies for the function invocations in each batch.
///
/// The iterator is normally infinite but it can be finite. If a finite iterator is used
/// with the benchmarking functions, the benchmark will end prematurely if the iterator is exhausted
/// before the specified benchmark run length.
pub trait LatencySrc<const K: usize>: Iterator<Item = [FpSeconds; K]> {
    /// Returns an iterator that yields the sum of the `[FpSeconds; K]` generated by `self` multiplied by `n`,
    /// where `n` is given by [`batch()`](Self::batch)` == Some(n)` with `n > 0` or `1` otherwise.
    fn aggregate(&mut self) -> impl Iterator<Item = FpSeconds> {
        let mult = self.batch().unwrap_or(1).max(1);
        self.map(move |arr| arr.map(|fps| fps * mult).iter().cloned().sum())
    }

    /// Returns whether batching was used and, if so, what it was.
    fn batch(&self) -> Option<usize>;

    /// Batch size used in data collection. Returns `1` for [`batch()`](Self::batch) values of `None`, `Some(0)`,
    /// and `Some(1)`.
    fn batch_size(&self) -> usize {
        self.batch().unwrap_or(1).max(1)
    }
}

impl<const K: usize, T: LatencySrc<K>> LatencySrc<K> for &mut T {
    fn batch(&self) -> Option<usize> {
        (**self).batch()
    }
}

/// A [`LatencySrc`] that yields the latency of the invocation of a single closure on each
/// call to `next()`.
pub struct LatencySrc1<F: FnMut()> {
    f: F,
}

impl<F: FnMut()> LatencySrc1<F> {
    /// Returns an instance of `Self`.
    pub fn new(f: F) -> Self {
        Self { f }
    }
}

impl<F: FnMut()> Iterator for LatencySrc1<F> {
    type Item = [FpSeconds; 1];

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        Some([latency(&mut self.f).into()])
    }
}

impl<F: FnMut()> LatencySrc<1> for LatencySrc1<F> {
    fn batch(&self) -> Option<usize> {
        None
    }
}

/// A [`LatencySrc`] that yields the latencies of the invocations of two closures on each
/// call to `next()`.
pub struct LatencySrc2<F1: FnMut(), F2: FnMut()> {
    f1: F1,
    f2: F2,
}

impl<F1: FnMut(), F2: FnMut()> LatencySrc2<F1, F2> {
    /// Returns an instance of `Self`.
    pub fn new(f1: F1, f2: F2) -> Self {
        Self { f1, f2 }
    }
}

impl<F1: FnMut(), F2: FnMut()> Iterator for LatencySrc2<F1, F2> {
    type Item = [FpSeconds; 2];

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        Some([latency(&mut self.f1).into(), latency(&mut self.f2).into()])
    }
}

impl<F1: FnMut(), F2: FnMut()> LatencySrc<2> for LatencySrc2<F1, F2> {
    fn batch(&self) -> Option<usize> {
        None
    }
}

/// A [`LatencySrc`] that batches invocations of a single `f` into groups of size `batch` and yields
/// the average latency of each group `batch` times before proceding to the next group execution.
pub struct LatencySrc1b<F: FnMut()> {
    /// Target closure
    f: F,
    /// Batch size
    batch: usize,
}

impl<F1: FnMut()> LatencySrc1b<F1> {
    /// Returns an instance of `Self`.
    pub fn new(f: F1, batch: usize) -> Self {
        Self { f, batch }
    }
}

impl<F: FnMut()> Iterator for LatencySrc1b<F> {
    type Item = [FpSeconds; 1];

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        let batch = self.batch;
        let value = latency_n(&mut self.f, batch).as_secs_f64() / batch as f64;
        Some([value.into()])
    }
}

impl<F1: FnMut()> LatencySrc<1> for LatencySrc1b<F1> {
    fn batch(&self) -> Option<usize> {
        Some(self.batch)
    }
}

/// A [`LatencySrc`] that batches invocations of two closures` into groups of size `batch` and yields
/// the respective average latencies of the closures for each group `batch` times before proceding
/// to the next group execution..
pub struct LatencySrc2b<F1: FnMut(), F2: FnMut()> {
    f1: F1,
    f2: F2,
    batch: usize,
}

impl<F1: FnMut(), F2: FnMut()> LatencySrc2b<F1, F2> {
    /// Returns an instance of `Self`.
    pub fn new(f1: F1, f2: F2, batch: usize) -> Self {
        Self { f1, f2, batch }
    }
}

impl<F1: FnMut(), F2: FnMut()> Iterator for LatencySrc2b<F1, F2> {
    type Item = [FpSeconds; 2];

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        let batch = self.batch;
        let value1 = latency_n(&mut self.f1, batch).as_secs_f64() / batch as f64;
        let value2 = latency_n(&mut self.f2, batch).as_secs_f64() / batch as f64;
        Some([value1.into(), value2.into()])
    }
}

impl<F1: FnMut(), F2: FnMut()> LatencySrc<2> for LatencySrc2b<F1, F2> {
    fn batch(&self) -> Option<usize> {
        Some(self.batch)
    }
}

#[cfg(feature = "_test_support")]
pub mod test_support {
    use std::time::Instant;

    use super::*;
    use basic_stats::normal::lognormal_rand_gen;

    /// Empty latency source.
    pub struct EmptyLatencySrc<const K: usize>;

    impl<const K: usize> Iterator for EmptyLatencySrc<K> {
        type Item = [FpSeconds; K];

        fn next(&mut self) -> Option<Self::Item> {
            None
        }
    }

    impl<const K: usize> LatencySrc<K> for EmptyLatencySrc<K> {
        fn batch(&self) -> Option<usize> {
            None
        }
    }

    /// Infinite source that always yields the same value. Useful for troubleshooting.
    pub struct ConstLatencySrc<const K: usize> {
        latencies: [FpSeconds; K],
        batch: usize,
    }

    impl<const K: usize> ConstLatencySrc<K> {
        pub fn new(latencies: [FpSeconds; K], batch: usize) -> Self {
            Self { latencies, batch }
        }
    }

    impl<const K: usize> Iterator for ConstLatencySrc<K> {
        type Item = [FpSeconds; K];

        fn next(&mut self) -> Option<Self::Item> {
            Some(self.latencies)
        }
    }

    impl<const K: usize> LatencySrc<K> for ConstLatencySrc<K> {
        fn batch(&self) -> Option<usize> {
            Some(self.batch)
        }
    }

    /// A [`LatencySrc`] that yields `Instant::now().elapsed()` on each call to `next()`.
    pub struct LatencySrc0;

    impl Iterator for LatencySrc0 {
        type Item = [FpSeconds; 1];

        #[inline(always)]
        fn next(&mut self) -> Option<Self::Item> {
            Some([(Instant::now().elapsed()).into()])
        }
    }

    impl LatencySrc<1> for LatencySrc0 {
        fn batch(&self) -> Option<usize> {
            None
        }
    }

    /// An infinite iterator that encapsulates `K` iterators, each of which emits [`FpSeconds`] values according to
    /// a lognormal distribution.
    ///
    /// This iterator's `next()` method yields a `[FpSeconds; K]`, each component of which draws from the corresonding
    /// encapsulated iterator.
    pub struct LognormalLatencySrc<const K: usize> {
        generators: [Box<dyn Iterator<Item = FpSeconds>>; K],
        batch: usize,
    }

    impl<const K: usize> LognormalLatencySrc<K> {
        /// Instantiates `Self`.
        ///
        /// The argument is an array of pairs of targets and sigmas that determine the probability distributions of the
        /// `K` component iterators:
        /// - each target is the target median latency for the component;
        /// - each sigma is the standard deviation for the natural logarithm of the component's probability distribution.
        pub fn new(targets_sigmas: [(FpSeconds, f64); K], batch: usize) -> Self {
            assert!(
                targets_sigmas.iter().all(|(m, s)| m.0 > 0.0 && *s > 0.0),
                "all target medians and sigmas must be positive"
            );

            let generators = targets_sigmas.map(|(target, sigma)| {
                let gen_f64 = lognormal_rand_gen(target.as_f64().ln(), sigma)
                    .expect("`target medians` and `sigmas` must all be `> 0`");
                let gen_dur = gen_f64.map(|v| FpSeconds(v));
                let boxed_gen: Box<dyn Iterator<Item = FpSeconds>> = Box::new(gen_dur);
                boxed_gen
            });

            Self { generators, batch }
        }

        /// Instantiates `Self` with default sigmas for the underlying lognormal distributions.
        ///
        /// The argument is an array of the target medians of the `K` component iterators.
        /// The distributions' sigmas are set to a default value.
        pub fn new_with_default_sigmas(targets: [FpSeconds; K], batch: usize) -> Self {
            // At 2 standard deviations of the underlying normal distribution, the latency is `multiplier` times the median latency.
            const MULTIPLIER: f64 = 1.15;
            let default_sigma = MULTIPLIER.ln() / 2.;

            assert!(
                targets.iter().all(|m| m.0 > 0.0),
                "all target medians must be positive"
            );

            let targets_sigmas = targets.map(|m| (m, default_sigma));
            Self::new(targets_sigmas, batch)
        }
    }

    impl<const K: usize> Iterator for LognormalLatencySrc<K> {
        type Item = [FpSeconds; K];

        fn next(&mut self) -> Option<Self::Item> {
            let mut batch_latencies = [FpSeconds::ZERO; K];
            for _ in 0..self.batch {
                for (k, lat) in batch_latencies.iter_mut().enumerate() {
                    *lat += self.generators[k]
                        .next()
                        .expect("`lognormal_detm_gen(,,).next()` can't return `None`");
                }
            }

            let mean_latencies = batch_latencies.map(|lat| lat / self.batch);

            Some(mean_latencies)
        }
    }

    impl<const K: usize> LatencySrc<K> for LognormalLatencySrc<K> {
        fn batch(&self) -> Option<usize> {
            Some(self.batch)
        }
    }

    #[cfg(test)]
    mod test {
        use super::*;
        use crate::{BenchCfg, multi::BenchOut};
        use basic_stats::rel_approx_eq;
        use std::panic::catch_unwind;

        #[test]
        // cargo test --package bench_utils --lib --all-features -- multi::latency_src::test_support::test::test_lognormal_src --exact --nocapture --include-ignored
        fn test_lognormal_src() {
            const EPSILON: f64 = 0.002;
            const SAMP_SIZE: usize = 1000;

            let cfg = BenchCfg::default();
            let targets = [
                FpSeconds::from_nanos(10),
                FpSeconds::from_micros(20),
                FpSeconds::from_millis(30),
            ];
            let src = LognormalLatencySrc::new_with_default_sigmas(targets, 2);
            let mut out = BenchOut::new(&cfg, None);
            out.record_from_iter(src.take(SAMP_SIZE));
            let out_medians = out.medians();

            println!(
                "*** src[0]={:?}",
                LognormalLatencySrc::new_with_default_sigmas(targets, 2)
                    .take(20)
                    .collect::<Vec<_>>()
            );

            rel_approx_eq!(targets[0].0, out_medians[0].0, EPSILON);
            rel_approx_eq!(targets[1].0, out_medians[1].0, EPSILON);
            rel_approx_eq!(targets[2].0, out_medians[2].0, EPSILON);
        }

        #[test]
        fn test_const_latency_src() {
            let mut src = ConstLatencySrc::<2>::new(
                [FpSeconds::from_millis(1), FpSeconds::from_millis(2)],
                1,
            );
            for _ in 0..5 {
                assert_eq!(
                    src.next(),
                    Some([FpSeconds::from_millis(1), FpSeconds::from_millis(2)])
                );
            }

            let m1 = 1;
            let m2 = 2;
            let batch = 42;
            let count = 2;
            let mut src2 = ConstLatencySrc::<2>::new(
                [FpSeconds::from_millis(m1), FpSeconds::from_millis(m2)],
                batch,
            );
            let sum: FpSeconds = src2.aggregate().take(count).sum();
            assert_eq!(
                sum,
                FpSeconds::from_millis(count as u64 * batch as u64 * (m1 + m2))
            );
        }

        #[test]
        fn test_empty_latency_src() {
            let mut src = EmptyLatencySrc::<1>;
            assert_eq!(src.next(), None);

            let mut src2 = EmptyLatencySrc::<1>;
            assert_eq!(src2.aggregate().next(), None);

            let cfg = BenchCfg::default();
            let mut out = BenchOut::new(&cfg, None);
            out.record_from_iter(EmptyLatencySrc::<1>);
            assert_eq!(out.n(), 0);
        }

        #[test]
        fn test_lognormal_latency_src_new() {
            let cfg = BenchCfg::default();
            let target = FpSeconds::from_millis(10);
            let src = LognormalLatencySrc::<1>::new([(target, 0.2)], 3);
            let mut out = BenchOut::new(&cfg, None);
            out.record_from_iter(src.take(2000));
            let medians = out.medians();
            rel_approx_eq!(medians[0].0, target.0, 0.05);

            let result = catch_unwind(|| {
                LognormalLatencySrc::<1>::new([(FpSeconds::ZERO, 0.2)], 1);
            });
            assert!(result.is_err(), "expected panic for zero median");

            let result = catch_unwind(|| {
                LognormalLatencySrc::<1>::new([(FpSeconds::from_millis(10), 0.0)], 2);
            });
            assert!(result.is_err(), "expected panic for zero sigma");
        }
    }
}
