use crate::latency;
use std::time::Duration;

/// An infinite iterator that encapsulates `K` closures and, for each invocation
/// of `next()`, yields an array of size `K` with the wall-clock latency durations from
/// [`group_size`](Self::group_size) invocations of each of the `K` closures.
///
/// The iterator doesn't have to be infinite, though normally it would be. If a finite iterator is used
/// with the benchmarking functions, the benchmark will end prematurely if the iterator is exhausted
/// before the specified benchmark run length.
pub trait LatencySrc<const K: usize>: Iterator<Item = [Duration; K]> {
    /// Returns the group size. Grouped latency sources should implement this method rather than
    /// use the provided implementation.
    #[inline(always)]
    fn group_size(&self) -> u32 {
        1
    }

    /// Returns an iterator that yields the sum of each `[Duration; K]` generated by `self`.
    fn aggregate(&mut self) -> impl Iterator<Item = Duration> {
        self.map(|arr| arr.iter().sum())
    }
}

impl<const K: usize, T: LatencySrc<K>> LatencySrc<K> for &mut T {}

/// Infinite iterator that yields the latency of the invocation of a single closure on each
/// call to `next()`.
pub struct LatencySrc1<F0: FnMut()>(pub F0);

impl<F0: FnMut()> Iterator for LatencySrc1<F0> {
    type Item = [Duration; 1];

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        Some([latency(&mut self.0)])
    }
}

impl<F0: FnMut()> LatencySrc<1> for LatencySrc1<F0> {}

/// Infinite iterator that yields the latencies of the invocations of two closures on each
/// call to `next()`.
pub struct LatencySrc2<F0: FnMut(), F1: FnMut()>(pub F0, pub F1);

impl<F0: FnMut(), F1: FnMut()> Iterator for LatencySrc2<F0, F1> {
    type Item = [Duration; 2];

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        Some([latency(&mut self.0), latency(&mut self.1)])
    }
}

impl<F0: FnMut(), F1: FnMut()> LatencySrc<2> for LatencySrc2<F0, F1> {}

/// Infinite iterator that yields the total latency of `group_size` invocations of a single closure
/// on each call to `next()`.
pub struct LatencySrcGrouped1<F0: FnMut()>(pub F0, pub u32);

impl<F0: FnMut()> Iterator for LatencySrcGrouped1<F0> {
    type Item = [Duration; 1];

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        Some([latency(|| {
            for _ in 0..self.group_size() {
                self.0()
            }
        })])
    }
}

impl<F0: FnMut()> LatencySrc<1> for LatencySrcGrouped1<F0> {
    #[inline(always)]
    fn group_size(&self) -> u32 {
        self.1
    }
}

/// Infinite iterator that yields the respective total latencies of `G` invocations of each
/// of two closures on each call to `next()`.
pub struct LatencySrcGrouped2<F0: FnMut(), F1: FnMut()>(pub F0, pub F1, pub u32);

impl<F0: FnMut(), F1: FnMut()> Iterator for LatencySrcGrouped2<F0, F1> {
    type Item = [Duration; 2];

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        Some([
            latency(|| {
                for _ in 0..self.group_size() {
                    self.0()
                }
            }),
            latency(|| {
                for _ in 0..self.group_size() {
                    self.1()
                }
            }),
        ])
    }
}

impl<F0: FnMut(), F1: FnMut()> LatencySrc<2> for LatencySrcGrouped2<F0, F1> {
    #[inline(always)]
    fn group_size(&self) -> u32 {
        self.2
    }
}

#[cfg(feature = "_test_support")]
pub mod test_support {
    use super::*;
    use basic_stats::normal::lognormal_rand_gen;
    use std::array;

    /// Empty latency source.
    pub struct EmptyLatencySrc<const K: usize>;

    impl<const K: usize> Iterator for EmptyLatencySrc<K> {
        type Item = [Duration; K];

        fn next(&mut self) -> Option<Self::Item> {
            None
        }
    }

    impl<const K: usize> LatencySrc<K> for EmptyLatencySrc<K> {}

    /// Infinite source that always yields the same value. Useful for troubleshooting.
    pub struct ConstLatencySrc<const K: usize> {
        latencies: [Duration; K],
    }

    impl<const K: usize> ConstLatencySrc<K> {
        pub fn new(latencies: [Duration; K]) -> Self {
            Self { latencies }
        }
    }

    impl<const K: usize> Iterator for ConstLatencySrc<K> {
        type Item = [Duration; K];

        fn next(&mut self) -> Option<Self::Item> {
            Some(self.latencies)
        }
    }

    impl<const K: usize> LatencySrc<K> for ConstLatencySrc<K> {}

    /// An infinite iterator that encapsulates `K` iterators, each of which emits [`Duration`] values according to
    /// a lognormal distribution.
    ///
    /// This iterator's `next()` method yields a `[Duration; K]`, each component of which draws from the corresonding
    /// encapsulated iterator.
    pub struct LognormalLatencySrc<const K: usize> {
        generators: [Box<dyn Iterator<Item = Duration>>; K],
    }

    impl<const K: usize> LognormalLatencySrc<K> {
        /// Instantiates `Self`.
        ///
        /// The argument is an array of pairs of targets and sigmas that determine the probability distributions of the
        /// `K` component iterators:
        /// - each target is the target median latency for the component;
        /// - each sigma is the standard deviation for the natural logarithm of the component's probability distribution.
        pub fn new(targets_sigmas: [(Duration, f64); K]) -> Self {
            assert!(
                targets_sigmas
                    .iter()
                    .all(|(m, s)| *m > Duration::ZERO && *s > 0.0),
                "all medians and sigmas must be positive"
            );

            let generators = targets_sigmas.map(|(target, sigma)| {
                let gen_f64 = lognormal_rand_gen(target.as_secs_f64().ln(), sigma)
                    .expect("`target medians` and `sigmas` must all be `> 0`");
                let gen_dur = gen_f64.map(|v| Duration::from_secs_f64(v));
                let boxed_gen: Box<dyn Iterator<Item = Duration>> = Box::new(gen_dur);
                boxed_gen
            });

            Self { generators }
        }

        /// Instantiates `Self` with default sigmas for the underlying lognormal distributions.
        ///
        /// The argument is an array of the target medians of the `K` component iterators.
        /// The distributions' sigmas are set to a default value.
        pub fn new_with_default_sigmas(targets: [Duration; K]) -> Self {
            // At 2 standard deviations of the underlying normal distribution, the latency is `multiplier` times the median latency.
            const MULTIPLIER: f64 = 1.15;
            let default_sigma = MULTIPLIER.ln() / 2.;

            assert!(
                targets.iter().all(|m| *m > Duration::ZERO),
                "all `target medians` must be positive"
            );

            let targets_sigmas = targets.map(|m| (m, default_sigma));
            Self::new(targets_sigmas)
        }
    }

    impl<const K: usize> Iterator for LognormalLatencySrc<K> {
        type Item = [Duration; K];

        fn next(&mut self) -> Option<Self::Item> {
            let durations = array::from_fn(|i| {
                self.generators[i]
                    .next()
                    .expect("`lognormal_detm_gen(,,).next()` can't return `None`")
            });
            Some(durations)
        }
    }

    impl<const K: usize> LatencySrc<K> for LognormalLatencySrc<K> {}

    /// Infinite iterator that genearates durations that converge to a `target_latency`.
    pub struct ConvergingDurationIterator {
        target_latency: Duration,
        iteration: u64,
    }

    impl ConvergingDurationIterator {
        pub fn new(target_latency: Duration) -> Self {
            Self {
                target_latency,
                iteration: 0,
            }
        }
    }

    impl Iterator for ConvergingDurationIterator {
        type Item = Duration;

        fn next(&mut self) -> Option<Self::Item> {
            self.iteration += 1;
            let sign = if self.iteration % 2 == 1 { 1.0 } else { -1.0 };
            let value = self
                .target_latency
                .mul_f64(1.0 + sign / self.iteration as f64);
            Some(value)
        }
    }

    /// Latency source that encapsulates an array of [`ConvergingLatencyIterator`]s.
    pub struct ConvergingLatencySrc<const K: usize> {
        iters: [ConvergingDurationIterator; K],
    }

    impl<const K: usize> ConvergingLatencySrc<K> {
        pub fn new(target_latencies: [Duration; K]) -> Self {
            Self {
                iters: target_latencies.map(|ltn| ConvergingDurationIterator::new(ltn)),
            }
        }

        pub fn target_latencies(&self) -> [Duration; K] {
            array::from_fn(|k| self.iters[k].target_latency)
        }
    }

    impl<const K: usize> Iterator for ConvergingLatencySrc<K> {
        type Item = [Duration; K];

        fn next(&mut self) -> Option<Self::Item> {
            let opts = array::from_fn(|k| self.iters[k].next());
            if opts.iter().all(|v| v.is_some()) {
                let res = opts.map(|v| v.expect("must be Some"));
                Some(res)
            } else {
                None
            }
        }
    }

    impl<const K: usize> LatencySrc<K> for ConvergingLatencySrc<K> {}

    #[cfg(test)]
    mod test {
        use super::*;
        use crate::{BenchCfg, multi::BenchOut, rel_approx_eq_dur};
        use basic_stats::rel_approx_eq;
        use std::panic::catch_unwind;

        #[test]
        // cargo test --package bench_utils --lib --all-features -- multi::latency_src::test_support::test::test_lognormal_src --exact --nocapture --include-ignored
        fn test_lognormal_src() {
            const EPSILON: f64 = 0.002;
            const SAMP_SIZE: usize = 1000;

            let cfg = BenchCfg::default();
            let targets = [
                Duration::from_nanos(10),
                Duration::from_micros(20),
                Duration::from_millis(30),
            ];
            let src = LognormalLatencySrc::new_with_default_sigmas(targets);
            let out = BenchOut::from_iter(&cfg, src.take(SAMP_SIZE));
            let out_medians = out.medians();

            println!(
                "*** src[0]={:?}",
                LognormalLatencySrc::new_with_default_sigmas(targets)
                    .take(20)
                    .collect::<Vec<_>>()
            );

            rel_approx_eq_dur!(targets[0], out_medians[0], EPSILON);
            rel_approx_eq_dur!(targets[1], out_medians[1], EPSILON);
            rel_approx_eq_dur!(targets[2], out_medians[2], EPSILON);
        }

        #[test]
        fn test_const_latency_src() {
            let mut src =
                ConstLatencySrc::<2>::new([Duration::from_millis(1), Duration::from_millis(2)]);
            for _ in 0..5 {
                assert_eq!(
                    src.next(),
                    Some([Duration::from_millis(1), Duration::from_millis(2)])
                );
            }

            let mut src2 =
                ConstLatencySrc::<2>::new([Duration::from_millis(1), Duration::from_millis(2)]);
            let sum: Duration = src2.aggregate().take(3).sum();
            assert_eq!(sum, Duration::from_millis(9));
        }

        #[test]
        fn test_empty_latency_src() {
            let mut src = EmptyLatencySrc::<1>;
            assert_eq!(src.next(), None);

            let mut src2 = EmptyLatencySrc::<1>;
            assert_eq!(src2.aggregate().next(), None);

            let cfg = BenchCfg::default();
            let out = BenchOut::from_iter(&cfg, EmptyLatencySrc::<1>);
            assert_eq!(out.n(), 0);
        }

        #[test]
        fn test_converging_latency_src() {
            let target = Duration::from_millis(10);
            let src = ConvergingLatencySrc::<1>::new([target]);
            assert_eq!(src.target_latencies(), [target]);

            let items: Vec<[Duration; 1]> = src.take(10).collect();
            let mut prev_gap = f64::MAX;
            for (i, item) in items.iter().enumerate() {
                let dur = item[0];
                let above = dur > target;
                assert!(
                    above == (i % 2 == 0),
                    "iteration {i}: {dur:?} should be {} target",
                    if i % 2 == 0 { "above" } else { "below" }
                );
                let gap = if above { dur - target } else { target - dur };
                let gap_secs = gap.as_secs_f64();
                assert!(
                    gap_secs < prev_gap,
                    "iteration {i}: gap {gap_secs} not smaller than prev {prev_gap}"
                );
                prev_gap = gap_secs;
            }

            let src2 = ConvergingLatencySrc::<1>::new([target]);
            let total: Duration = src2.take(1000).map(|arr| arr[0]).sum();
            let mean_secs = total.as_secs_f64() / 1000.0;
            let target_secs = target.as_secs_f64();
            rel_approx_eq!(mean_secs, target_secs, 0.01);
        }

        #[test]
        fn test_lognormal_latency_src_new() {
            let cfg = BenchCfg::default();
            let target = Duration::from_millis(10);
            let src = LognormalLatencySrc::<1>::new([(target, 0.2)]);
            let out = BenchOut::from_iter(&cfg, src.take(2000));
            let medians = out.medians();
            rel_approx_eq_dur!(medians[0], target, 0.05);

            let result = catch_unwind(|| {
                LognormalLatencySrc::<1>::new([(Duration::ZERO, 0.2)]);
            });
            assert!(result.is_err(), "expected panic for zero median");

            let result = catch_unwind(|| {
                LognormalLatencySrc::<1>::new([(Duration::from_millis(10), 0.0)]);
            });
            assert!(result.is_err(), "expected panic for zero sigma");
        }
    }
}
