use crate::{FpSeconds, latency, latency_n};
use std::iter;

/// An infinite iterator that encapsulates `K` closures and yields their latencies from individual executions
/// or from bulk executions.
///
/// For each invocation of `next()`, the iterator yields a pair `(arr, n)`:
/// - `arr` is an array of size `K` with latencies associated with invocations of each of the `K` closures.
/// - `n` is the number of times the array value should be counted. It is `1` if each function is executed in each
///   iteration and `> 1` if each function is executed `n` times for each invocation of `next()`. In the latter
/// case, the `arr` value contains the mean of each function's latency over the `n` executions.
///
/// The iterator doesn't have to be infinite, though normally it would be. If a finite iterator is used
/// with the benchmarking functions, the benchmark will end prematurely if the iterator is exhausted
/// before the specified benchmark run length.
pub trait LatencySrc<const K: usize>: Iterator<Item = ([FpSeconds; K], usize)> {
    /// Returns an iterator that, for each pair `(arr, n)` yielded by `self`, yields `arr` `n` times.
    fn dole_out(&mut self) -> impl Iterator<Item = [FpSeconds; K]> {
        self.map(|(value, count)| iter::repeat_n(value, count))
            .flatten()
    }

    /// Returns an iterator that yields the sum of each `[FpSeconds; K]` generated by `self`.
    fn aggregate(&mut self) -> impl Iterator<Item = FpSeconds> {
        self.dole_out().map(|arr| arr.iter().cloned().sum())
    }
}

impl<const K: usize, T: LatencySrc<K>> LatencySrc<K> for &mut T {}

/// A [`LatencySrc`] that yields the latency of the invocation of a single closure on each
/// call to `next()`.
pub struct LatencySrc1<F: FnMut()> {
    f: F,
}

impl<F: FnMut()> LatencySrc1<F> {
    /// Returns an instance of `Self`.
    pub fn new(f: F) -> Self {
        Self { f }
    }
}

impl<F: FnMut()> Iterator for LatencySrc1<F> {
    type Item = ([FpSeconds; 1], usize);

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        Some(([latency(&mut self.f).into()], 1))
    }
}

impl<F: FnMut()> LatencySrc<1> for LatencySrc1<F> {}

/// A [`LatencySrc`] that yields the latencies of the invocations of two closures on each
/// call to `next()`.
pub struct LatencySrc2<F1: FnMut(), F2: FnMut()> {
    f1: F1,
    f2: F2,
}

impl<F1: FnMut(), F2: FnMut()> LatencySrc2<F1, F2> {
    /// Returns an instance of `Self`.
    pub fn new(f1: F1, f2: F2) -> Self {
        Self { f1, f2 }
    }
}

impl<F1: FnMut(), F2: FnMut()> Iterator for LatencySrc2<F1, F2> {
    type Item = ([FpSeconds; 2], usize);

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        Some((
            [latency(&mut self.f1).into(), latency(&mut self.f2).into()],
            1,
        ))
    }
}

impl<F1: FnMut(), F2: FnMut()> LatencySrc<2> for LatencySrc2<F1, F2> {}

/// A [`LatencySrc`] that batches invocations of a single `f` into groups of size `batch` and yields
/// the average latency of each group `batch` times before proceding to the next group execution.
pub struct LatencySrc1b<F: FnMut()> {
    /// Target closure
    f: F,
    /// Batch size
    batch: usize,
}

impl<F1: FnMut()> LatencySrc1b<F1> {
    /// Returns an instance of `Self`.
    pub fn new(f: F1, batch: usize) -> Self {
        Self { f, batch }
    }
}

impl<F: FnMut()> Iterator for LatencySrc1b<F> {
    type Item = ([FpSeconds; 1], usize);

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        let batch = self.batch;
        let value = latency_n(&mut self.f, batch).as_secs_f64() / batch as f64;
        Some(([value.into()], batch))
    }
}

impl<F1: FnMut()> LatencySrc<1> for LatencySrc1b<F1> {}

/// A [`LatencySrc`] that batches invocations of two closures` into groups of size `batch` and yields
/// the respective average latencies of the closures for each group `batch` times before proceding
/// to the next group execution..
pub struct LatencySrc2b<F1: FnMut(), F2: FnMut()> {
    f1: F1,
    f2: F2,
    batch: usize,
}

impl<F1: FnMut(), F2: FnMut()> LatencySrc2b<F1, F2> {
    /// Returns an instance of `Self`.
    pub fn new(f1: F1, f2: F2, batch: usize) -> Self {
        Self { f1, f2, batch }
    }
}

impl<F1: FnMut(), F2: FnMut()> Iterator for LatencySrc2b<F1, F2> {
    type Item = ([FpSeconds; 2], usize);

    #[inline(always)]
    fn next(&mut self) -> Option<Self::Item> {
        let batch = self.batch;
        let value1 = latency_n(&mut self.f1, batch).as_secs_f64() / batch as f64;
        let value2 = latency_n(&mut self.f2, batch).as_secs_f64() / batch as f64;
        Some(([value1.into(), value2.into()], batch))
    }
}

impl<F1: FnMut(), F2: FnMut()> LatencySrc<2> for LatencySrc2b<F1, F2> {}

#[cfg(feature = "_test_support")]
pub mod test_support {
    use super::*;
    use basic_stats::normal::lognormal_rand_gen;

    /// Empty latency source.
    pub struct EmptyLatencySrc<const K: usize>;

    impl<const K: usize> Iterator for EmptyLatencySrc<K> {
        type Item = ([FpSeconds; K], usize);

        fn next(&mut self) -> Option<Self::Item> {
            None
        }
    }

    impl<const K: usize> LatencySrc<K> for EmptyLatencySrc<K> {}

    /// Infinite source that always yields the same value. Useful for troubleshooting.
    pub struct ConstLatencySrc<const K: usize> {
        latencies: [FpSeconds; K],
        batch: usize,
    }

    impl<const K: usize> ConstLatencySrc<K> {
        pub fn new(batch: usize, latencies: [FpSeconds; K]) -> Self {
            Self { latencies, batch }
        }
    }

    impl<const K: usize> Iterator for ConstLatencySrc<K> {
        type Item = ([FpSeconds; K], usize);

        fn next(&mut self) -> Option<Self::Item> {
            Some((self.latencies, self.batch))
        }
    }

    impl<const K: usize> LatencySrc<K> for ConstLatencySrc<K> {}

    /// An infinite iterator that encapsulates `K` iterators, each of which emits [`FpSeconds`] values according to
    /// a lognormal distribution.
    ///
    /// This iterator's `next()` method yields a `[FpSeconds; K]`, each component of which draws from the corresonding
    /// encapsulated iterator.
    pub struct LognormalLatencySrc<const K: usize> {
        generators: [Box<dyn Iterator<Item = FpSeconds>>; K],
        batch: usize,
    }

    impl<const K: usize> LognormalLatencySrc<K> {
        /// Instantiates `Self`.
        ///
        /// The argument is an array of pairs of targets and sigmas that determine the probability distributions of the
        /// `K` component iterators:
        /// - each target is the target median latency for the component;
        /// - each sigma is the standard deviation for the natural logarithm of the component's probability distribution.
        pub fn new(batch: usize, targets_sigmas: [(FpSeconds, f64); K]) -> Self {
            assert!(
                targets_sigmas.iter().all(|(m, s)| m.0 > 0.0 && *s > 0.0),
                "all target medians and sigmas must be positive"
            );

            let generators = targets_sigmas.map(|(target, sigma)| {
                let gen_f64 = lognormal_rand_gen(target.as_f64().ln(), sigma)
                    .expect("`target medians` and `sigmas` must all be `> 0`");
                let gen_dur = gen_f64.map(|v| FpSeconds(v));
                let boxed_gen: Box<dyn Iterator<Item = FpSeconds>> = Box::new(gen_dur);
                boxed_gen
            });

            Self { generators, batch }
        }

        /// Instantiates `Self` with default sigmas for the underlying lognormal distributions.
        ///
        /// The argument is an array of the target medians of the `K` component iterators.
        /// The distributions' sigmas are set to a default value.
        pub fn new_with_default_sigmas(batch: usize, targets: [FpSeconds; K]) -> Self {
            // At 2 standard deviations of the underlying normal distribution, the latency is `multiplier` times the median latency.
            const MULTIPLIER: f64 = 1.15;
            let default_sigma = MULTIPLIER.ln() / 2.;

            assert!(
                targets.iter().all(|m| m.0 > 0.0),
                "all target medians must be positive"
            );

            let targets_sigmas = targets.map(|m| (m, default_sigma));
            Self::new(batch, targets_sigmas)
        }
    }

    impl<const K: usize> Iterator for LognormalLatencySrc<K> {
        type Item = ([FpSeconds; K], usize);

        fn next(&mut self) -> Option<Self::Item> {
            let mut batch_latencies = [FpSeconds::ZERO; K];
            for _ in 0..self.batch {
                for (k, lat) in batch_latencies.iter_mut().enumerate() {
                    *lat += self.generators[k]
                        .next()
                        .expect("`lognormal_detm_gen(,,).next()` can't return `None`");
                }
            }

            let mean_latencies = batch_latencies.map(|lat| lat / self.batch);

            Some((mean_latencies, self.batch))
        }
    }

    impl<const K: usize> LatencySrc<K> for LognormalLatencySrc<K> {}

    #[cfg(test)]
    mod test {
        use super::*;
        use crate::{BenchCfg, multi::BenchOut};
        use basic_stats::rel_approx_eq;
        use std::panic::catch_unwind;

        #[test]
        // cargo test --package bench_utils --lib --all-features -- multi::latency_src::test_support::test::test_lognormal_src --exact --nocapture --include-ignored
        fn test_lognormal_src() {
            const EPSILON: f64 = 0.002;
            const SAMP_SIZE: usize = 1000;

            let cfg = BenchCfg::default();
            let targets = [
                FpSeconds::from_nanos(10),
                FpSeconds::from_micros(20),
                FpSeconds::from_millis(30),
            ];
            let mut src = LognormalLatencySrc::new_with_default_sigmas(2, targets);
            let out = BenchOut::from_iter(&cfg, src.dole_out().take(SAMP_SIZE));
            let out_medians = out.medians();

            println!(
                "*** src[0]={:?}",
                LognormalLatencySrc::new_with_default_sigmas(2, targets)
                    .take(20)
                    .collect::<Vec<_>>()
            );

            rel_approx_eq!(targets[0].0, out_medians[0].0, EPSILON);
            rel_approx_eq!(targets[1].0, out_medians[1].0, EPSILON);
            rel_approx_eq!(targets[2].0, out_medians[2].0, EPSILON);
        }

        #[test]
        fn test_const_latency_src() {
            let mut src = ConstLatencySrc::<2>::new(
                1,
                [FpSeconds::from_millis(1), FpSeconds::from_millis(2)],
            );
            for _ in 0..5 {
                assert_eq!(
                    src.next(),
                    Some(([FpSeconds::from_millis(1), FpSeconds::from_millis(2)], 1))
                );
            }

            let mut src2 = ConstLatencySrc::<2>::new(
                42,
                [FpSeconds::from_millis(1), FpSeconds::from_millis(2)],
            );
            let sum: FpSeconds = src2.aggregate().take(3).sum();
            assert_eq!(sum, FpSeconds::from_millis(9));
        }

        #[test]
        fn test_empty_latency_src() {
            let mut src = EmptyLatencySrc::<1>;
            assert_eq!(src.next(), None);

            let mut src2 = EmptyLatencySrc::<1>;
            assert_eq!(src2.aggregate().next(), None);

            let cfg = BenchCfg::default();
            let out = BenchOut::from_iter(&cfg, EmptyLatencySrc::<1>.dole_out());
            assert_eq!(out.n(), 0);
        }

        #[test]
        fn test_lognormal_latency_src_new() {
            let cfg = BenchCfg::default();
            let target = FpSeconds::from_millis(10);
            let mut src = LognormalLatencySrc::<1>::new(3, [(target, 0.2)]);
            let out = BenchOut::from_iter(&cfg, src.dole_out().take(2000));
            let medians = out.medians();
            rel_approx_eq!(medians[0].0, target.0, 0.05);

            let result = catch_unwind(|| {
                LognormalLatencySrc::<1>::new(1, [(FpSeconds::ZERO, 0.2)]);
            });
            assert!(result.is_err(), "expected panic for zero median");

            let result = catch_unwind(|| {
                LognormalLatencySrc::<1>::new(2, [(FpSeconds::from_millis(10), 0.0)]);
            });
            assert!(result.is_err(), "expected panic for zero sigma");
        }
    }
}
