//! Various types, traits, and functions that support testing.
//!
//! Gated by feature **"_test_support"**.

use crate::{BenchCfg, BenchOut, FpSeconds};
use basic_stats::{core::SampleMoments, normal::normal_detm_samp};
use std::{io::Write, sync::LazyLock, time::Duration};

/// Low log-standard-deviation value for test sample generation.
///
/// Computed as `ln(1.2) / 2`. Used to create lognormal samples with moderate variance.
pub static LO_STDEV_LN: LazyLock<f64> = LazyLock::new(|| 1.2_f64.ln() / 2.);

/// High log-standard-deviation value for test sample generation.
///
/// Computed as `ln(2.4) / 2`. Used to create lognormal samples with high variance.
pub static HI_STDEV_LN: LazyLock<f64> = LazyLock::new(|| 2.4_f64.ln() / 2.);

fn jitter(v: f64, i: i64, n_jitter: i64, epsilon: f64) -> f64 {
    assert!(n_jitter >= 3, "n_jitter must be >= 3");
    let max_jitter = (n_jitter - 1) / 2;
    let delta = (i % n_jitter - max_jitter) as f64 / max_jitter as f64 * epsilon;
    v + delta
}

/// Generates a deterministic lognormal [`FpSeconds`] sample with optional jitter.
///
/// First generates a normal sample from `Normal(mu, sigma)` using a deterministic method,
/// then exponentiates each value and casts to `u64`. A small epsilon jitter can be added
/// to deterministically simulate randomness in a simple way
/// (can also break ties from casting to `u64`).
///
/// # Arguments
///
/// - `mu` - mean of the underlying normal distribution (seconds log-scale).
/// - `sigma` - standard deviation of the underlying normal distribution (log-scale).
/// - `samp_size` - sample size.
/// - `n_jitter` - denominator controlling the jitter period (must be >= 3).
/// - `jitter_epsilon` - maximum magnitude of the jitter added to each value.
pub fn lognormal_samp_jittered(
    mu: f64,
    sigma: f64,
    samp_size: usize,
    n_jitter: i64,
    jitter_epsilon: f64,
) -> impl Iterator<Item = FpSeconds> {
    let normal_samp = normal_detm_samp(mu, sigma, samp_size).unwrap();
    normal_samp
        .enumerate()
        .map(move |(i, v)| jitter(v, i as i64, n_jitter, jitter_epsilon))
        .map(|x| FpSeconds(x.exp()))
}

/// Generates a deterministic lognormal [`FpSeconds`] sample without jitter.
///
/// Equivalent to [`lognormal_samp_jittered`] with `n_jitter=3` and `jitter_epsilon=0.0`.
///
/// # Arguments
///
/// - `mu` - mean of the underlying normal distribution (log-scale).
/// - `sigma` - standard deviation of the underlying normal distribution (log-scale).
/// - `samp_size` - sample size.
pub fn lognormal_samp(mu: f64, sigma: f64, samp_size: usize) -> impl Iterator<Item = FpSeconds> {
    lognormal_samp_jittered(mu, sigma, samp_size, 3, 0.)
}

/// Creates a [`BenchOut`] populated with a jittered lognormal sample.
///
/// The sample is generated by [`lognormal_samp_jittered`] and each item is converted
/// to a [`std::time::FpSeconds`] via [`FpSeconds::from_secs_f64`].
///
/// # Arguments
///
/// - `cfg` - benchmark configuration (recording unit, etc.).
/// - `mu` - mean of the underlying normal distribution (log-scale).
/// - `sigma` - standard deviation of the underlying normal distribution (log-scale).
/// - `samp_size` - sample size.
/// - `n_jitter` - denominator controlling the jitter period (must be >= 3).
/// - `jitter_epsilon` - maximum magnitude of the jitter added to each value.
pub fn lognormal_out_jittered(
    cfg: &BenchCfg,
    mu: f64,
    sigma: f64,
    samp_size: usize,
    n_jitter: i64,
    jitter_epsilon: f64,
) -> BenchOut {
    let lognormal_samp = lognormal_samp_jittered(mu, sigma, samp_size, n_jitter, jitter_epsilon);
    BenchOut::from_iter(cfg, lognormal_samp)
}

/// Creates a [`BenchOut`] populated with a non-jittered lognormal sample.
///
/// Equivalent to [`lognormal_out_jittered`] with `n_jitter=3` and `jitter_epsilon=0.0`.
///
/// # Arguments
///
/// - `cfg` - benchmark configuration.
/// - `mu` - mean of the underlying normal distribution (log-scale).
/// - `sigma` - standard deviation of the underlying normal distribution (log-scale).
/// - `k` - controls the sample size; the total number of items is `2*k*k - 1`.
pub fn lognormal_out(cfg: &BenchCfg, mu: f64, sigma: f64, k: usize) -> BenchOut {
    lognormal_out_jittered(cfg, mu, sigma, k, 3, 0.)
}

/// Computes sample moments (sum, sum of squares, count) of the natural logarithms
/// of a jittered lognormal sample, for the specified latency recording unit.
///
/// # Arguments
///
/// - `mu` - mean of the underlying normal distribution (seconds log-scale).
/// - `sigma` - standard deviation of the underlying normal distribution (log-scale).
/// - `samp_size` - sample size.
/// - `n_jitter` - denominator controlling the jitter period (must be >= 3).
/// - `jitter_epsilon` - maximum magnitude of the jitter added to each value.
pub fn lognormal_moments_ln_jittered(
    mu: f64,
    sigma: f64,
    samp_size: usize,
    n_jitter: i64,
    jitter_epsilon: f64,
) -> SampleMoments {
    let dataset = lognormal_samp_jittered(mu, sigma, samp_size, n_jitter, jitter_epsilon)
        .filter_map(|latency| {
            if latency > FpSeconds::ZERO {
                Some(latency.as_f64().ln())
            } else {
                None
            }
        });
    SampleMoments::from_iterator(dataset)
}

/// Computes sample moments of the natural logarithms of a non-jittered lognormal sample,
/// for the specified latency recording unit.
///
/// Equivalent to [`lognormal_moments_ln_jittered`] with `n_jitter=3` and `jitter_epsilon=0.0`.
///
/// # Arguments
///
/// - `ru` - specified latency recording unit. The sample values are converted to and from
///   `ru` to ensure alignment with data capture in [`BenchOut`].
/// - `mu` - mean of the underlying normal distribution (log-scale).
/// - `sigma` - standard deviation of the underlying normal distribution (log-scale).
/// - `k` - controls the sample size; the total number of items is `2*k*k - 1`.
pub fn lognormal_moments_ln(mu: f64, sigma: f64, k: usize) -> SampleMoments {
    lognormal_moments_ln_jittered(mu, sigma, k, 3, 0.)
}

/// Writer backed by a [`Vec<u8>`] that can process backspace characters ("\u{8}") properly like stdout and stderr do.
///
/// Used for testing of status reporting by this crate and `bench_diff`.
pub struct StringWriter {
    buf: Vec<u8>,
}

impl Write for StringWriter {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        for byte in buf {
            if *byte == 8 {
                // backspace character
                let res = self
                    .buf
                    .pop()
                    .ok_or_else(|| {
                        std::io::Error::other("backspace being writen into empty `StringWriter`")
                    })
                    .map(|b| b as usize);
                #[allow(clippy::question_mark)]
                if res.is_err() {
                    return res;
                }
            } else {
                self.buf.push(*byte);
            }
        }

        Ok(buf.len())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

impl StringWriter {
    /// Creates a new empty `StringWriter`.
    pub fn new() -> Self {
        Self { buf: Vec::new() }
    }

    /// Returns the written content as a `&str`, validating UTF-8.
    pub fn as_str(&self) -> Result<&str, std::str::Utf8Error> {
        std::str::from_utf8(&self.buf)
    }
}

/// Returns the batch size required for a sample size of `samp_size` given a total observation count of
/// `total_count`.
pub fn batch_for_samp_size(samp_size: usize, total_count: usize) -> usize {
    assert!(
        total_count >= samp_size,
        "batch_for_samp_size >>> total_count={total_count} must be >= samp_size={samp_size}"
    );
    total_count / samp_size
}

/// Returns the batch size required for the batched execution of target latency `tgt_ltncy` to equal or
/// exceed `acc_ltncy`.
pub fn batch_for_acc_ltncy(tgt_ltncy: Duration, acc_ltncy: Duration) -> usize {
    acc_ltncy.as_nanos().div_ceil(tgt_ltncy.as_nanos()) as usize
}
